### ISSUE TITLE
A merge layer should be called on a list of inputs

### ISSUE THREAD

**Issue by liuyuer** [jhfjhfj1/autokeras#1]
Traceback (most recent call last):
  File "example.py", line 50, in <module>
    test_my_layer()
  File "example.py", line 39, in test_my_layer
    b = WeightedAdd()(a)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 590, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/merge.py", line 68, in build
    raise ValueError('A merge layer should be called '
ValueError: A merge layer should be called on a list of inputs.

Keras on Tensorflow 1.5

**Comment by jhfjhfj1** [comment]
Thank you for your report.
This bug is fixed in the latest release.

If you find it is not, please reopen the issue.

**Comment by olfaa** [comment]
Please can you help me I find the same error when I fine tune Unet architecture.
