### ISSUE TITLE
TimeoutError when running mnist.py

### ISSUE THREAD

**Issue by Jules-Diez** [jhfjhfj1/autokeras#108]
### Bug Description
When running mnist.py after some time, suddenly an error occurred : 

Traceback (most recent call last):
  File "/home/jdiez/project/AutoKeras/Test_01.py", line 11, in <module>
    clf.fit(x_train, y_train, time_limit=20 * 60)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/image_supervised.py", line 238, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/image_supervised.py", line 41, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/search.py", line 175, in search
    timeout)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/bayesian.py", line 272, in optimize_acq
    raise TimeoutError
TimeoutError

Process finished with exit code 1

### Reproducing Steps
  * Step 1: Follow the instruction steps for 0.2.4 install
  * Step 2: Run mnist.py

### Expected Behavior
Run without error

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 16.04 
 - Python: 3.6
 - autokeras: 0.2.4
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.2.2
 - scipy: 1.1.0
 - tensorflow: 1.8.0
 - pytorch: 0.4.1 (py36_cuda9.2.148_cudnn7.1.4_1)

### Additional context
Torch, Tensorflow and Keras are all working fine insisde this conda env.
The same error occurs when adapting the code for CIFAR10, Fashion-MNIST

**Comment by jhfjhfj1** [comment]
@Jules-Diez Thank you for your report.

I have solved it in the current master branch.

**Comment by Jules-Diez** [comment]
Ok I will try it tonight and see if it happens again or not.

**Comment by jhfjhfj1** [comment]
I think that is a normal behavior.
Thank you for your feedback! @Jules-Diez
