### ISSUE TITLE
MemoryError on mnist.py

### ISSUE THREAD

**Issue by Jules-Diez** [jhfjhfj1/autokeras#109]
### Bug Description
When running mnist.py after some time, suddenly an error occurred : 

.......Traceback (most recent call last):
  File "mnist.py", line 10, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/image_supervised.py", line 238, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/image_supervised.py", line 41, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/search.py", line 175, in search
    timeout)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/bayesian.py", line 257, in optimize_acq
    for temp_graph in transform(elem.graph):
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/net_transformer.py", line 85, in transform
    graphs.append(to_deeper_graph(deepcopy(graph)))
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/net_transformer.py", line 66, in to_deeper_graph
    graph.to_conv_deeper_model(layer_id, randint(1, 2) * 2 + 1)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/graph.py", line 313, in to_conv_deeper_model
    new_layers = deeper_conv_block(target, kernel_size, self.weighted)
  File "/home/jdiez/lib/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/layer_transformer.py", line 11, in deeper_conv_block
    weight = np.zeros((n_filters, n_filters) + filter_shape)
MemoryError

Process finished with exit code 1

### Reproducing Steps
  * Step 1: Follow the instruction steps for 0.2.4 install
  * Step 2: Run mnist.py

### Expected Behavior
Run without error

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 16.04 
 - Python: 3.6
 - autokeras: 0.2.4
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.2.2
 - scipy: 1.1.0
 - tensorflow: 1.8.0
 - pytorch: 0.4.1 (py36_cuda9.2.148_cudnn7.1.4_1)

### Additional context
Torch, Tensorflow and Keras are all working fine insisde this conda env.
The same error occurs when adapting the code for CIFAR10, Fashion-MNIST

**Comment by rckoepke** [comment]
I've encountered the same bug running:

Debian 9.5
TensorFlow 1.10
Python 3.6.6
keras 2.2.2

The error is not always reproducible. Sometimes running mnist.py results in no errors and a graceful exit after the 20th model converges.

**Comment by jhfjhfj1** [comment]
This is fixed in the latest release.
Thanks.
