### ISSUE TITLE
multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown

### ISSUE THREAD

**Issue by supermanhuyu** [jhfjhfj1/autokeras#154]
when i run cifar10 on my pc, its ok 
```
$ cat auto_keras.py 
from keras.datasets import cifar10
from autokeras.image_supervised import ImageClassifier

if __name__ == '__main__':
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    print(x_train.shape) 
    print(x_test.shape)
    clf = ImageClassifier(verbose=True)
    clf.fit(x_train, y_train, time_limit=5 * 60)
    clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
    y = clf.evaluate(x_test, y_test)
    print(y)

```

ant i run my dataset, i get the error of "out of memory"
the cifar10 dataset  x_train.shape  (50000, 32, 32, 3)
my dataset x_train.shape:   (99, 256, 256, 3)

my python script are like this : 
```
if __name__ == '__main__':
    x_train, y_train = data_load_user_defined(csv_file_path="data/cat_and_dog/train/train.csv",
                                     data_path="data/cat_and_dog/train")
    print(x_train.shape)
    # (99, 256, 256, 3)

    x_test, y_test = data_load_user_defined(csv_file_path="data/cat_and_dog/test/test.csv",
                                   data_path="data/cat_and_dog/test")
    print(x_test.shape)
    # (19, 256, 256, 3)

    clf = ImageClassifier(verbose=True)
    clf.fit(x_train, y_train, time_limit=30 * 60)
    clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
    y = clf.evaluate(x_test, y_test)
    print(y)
```

but i get the error:

```
$ python3.5 ak.py

(99, 256, 256, 3)  #x_train.shape
(19, 256, 256, 3)  #x_test.shape

Using TensorFlow backend.
Initializing search.
Initialization finished.


╒==============================================╕
|               Training model 0               |
╘==============================================╛
Using TensorFlow backend.
Current Epoch:   0%|                             | 0/1 [00:00<?, ? batch/s]Exception ignored in: <bound method tqdm.__del__ of     Model    :   0%|                           | 0/200 [00:00<?, ? epoch/s]>
Traceback (most recent call last):             | 0/200 [00:00<?, ? epoch/s]
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.close()
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 441, in _decr_instances
    cls._instances.remove(instance)
  File "/usr/lib/python3.5/_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x7fc9b753b958; to 'tqdm' at 0x7fc9b3fee048>
Exception ignored in: <bound method tqdm.__del__ of Current Epoch:   0%|                             | 0/1 [00:00<?, ? batch/s]>
Traceback (most recent call last):
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.close()
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 441, in _decr_instances
    cls._instances.remove(instance)
  File "/usr/lib/python3.5/_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x7fc9b753b958; to 'tqdm' at 0x7fc9b3fee2e8>
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/search.py", line 280, in train
    verbose).train_model(**trainer_args)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/utils.py", line 124, in train_model
    self._train()
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/utils.py", line 167, in _train
    outputs = self.model(inputs)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/graph.py", line 607, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ak.py", line 49, in <module>
    clf.fit(x_train, y_train, time_limit=5 * 60)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/image_supervised.py", line 238, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/image_supervised.py", line 41, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "/home/sg-ai-06/.local/lib/python3.5/site-packages/autokeras/search.py", line 210, in search
    metric_value, loss, graph = train_results.get(timeout=remaining_time)[0]
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
RuntimeError: CUDA error: out of memory
sg-ai-06@sg-ai-06:~$ /usr/lib/python3.5/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

```

**Comment by supermanhuyu** [comment]
when i change the sie of the function data_load_user_defined  out size to 32x32 , i can train it .maybe my GPU memory is too small .
