### ISSUE TITLE
cannot import name 'abs'

### ISSUE THREAD

**Issue by ddeeppnneett** [jhfjhfj1/autokeras#169]
Hi, 

After `pip install autokeras` with python3.6, I tried to run the mnist.py. But I got this error message, 

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from keras.datasets import mnist
  File "/usr/local/lib/python3.5/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 33, in <module>
    from tensorflow.python.keras import backend
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'
```

When I uninstall and reinstall tensorflow and keras with
```
pip uninstall tensorflow keras 
pip install tensorflow==1.10.0 keras=2.2.2
```
Still I got the same error.

Then I tried
```
pip uninstall tensorflow keras  protobuf 
find $CONDA_PREFIX -name "tensorflow" | xargs -Ipkg rm -rfv pkg
pip install tensorflow==1.10.0 keras=2.2.2
```
No luck. 

Finally, ` pip install tensorflow-gpu==1.10.0`  solve the problem. 

There is no error with  mnist.py any more. 
 
But when I tested my own code, I got another error, 

> Using TensorFlow backend.
>   #######
> width :  720
> batchsize :  8
> num_of_train :  900
> num_of_test :  100
>   #######
> shape of x_train :  (900, 720, 720, 1)
> shape of y_train :  (900, 10)
>  #######
> Traceback (most recent call last):
>   File "autok.py", line 77, in <module>
>     clf.fit(x_train, y_train)
>   File "/usr/local/lib/python3.5/dist-packages/autokeras/image_supervised.py", line 196, in fit
>     _validate(x_train, y_train)
>   File "/usr/local/lib/python3.5/dist-packages/autokeras/image_supervised.py", line 34, in _validate
>     raise ValueError('x_train and y_train should have the same number of instances.')
> ValueError: x_train and y_train should have the same number of instances.

What does this mean?

**Comment by jquach12** [comment]
Have you checked if you have a 1:1 labeling of your training data?

if x_train.shape[0] != y_train.shape[0]:
        raise ValueError('x_train and y_train should have the same number of instances.')

**Comment by jquach12** [comment]
Hmm, when working with MNIST and my own dataset, the shape of my x_train is similar to yours (number of samples, height, width, colorChannels), but my y_train has no second dimension.

**Comment by ddeeppnneett** [comment]
@jquach12 

First, as you said, 
```
if x_train.shape[0] != y_train.shape[0]:
raise ValueError('x_train and y_train should have the same number of instances.')
```
, I think, it has nothing to do with the second dimension. 

Second, I use this command in my code 
`y_train = np_utils.to_categorical(y_train,10)`. What does  

> my y_train has no second dimension 

 mean?  I should **not** pass the label  in the one-hot format? Or you use the  **Sigmoid** at the end?

**Comment by jhfjhfj1** [comment]
It should not be one-hot-encoded when feed to autokeras.

I assume this issue is resolved.
Thank you all for the contribution.
