### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by aojue1109** [jhfjhfj1/autokeras#184]
Training model 1  appear  problem
╒==============================================╕
|               Training model 1               |
╘==============================================╛
Current Epoch:   0%|                             | 0/6 [00:00<?, ? batch/s]Using TensorFlow backend.
    Model    :   0%|                           | 0/200 [00:00<?, ? epoch/s]Exception ignored in: <bound method tqdm.__del__ of Current Epoch:   0%|                             | 0/6 [10:01<?, ? batch/s]>                                                   
Traceback (most recent call last):
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.close()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by jhfjhfj1** [comment]
@aojue1109 
Please use the standard template to formulate your bug report.

Thanks.
