### ISSUE TITLE
RuntimeError: CUDA error (10): invalid device ordinal on multi-GPU machine

### ISSUE THREAD

**Issue by hiepph** [jhfjhfj1/autokeras#189]
### Bug Description

I tried running the MNIST example (https://autokeras.com/start/#example) on an 8-GPU machine but chose only 1 GPU to use, and this error popped up:

```
Traceback (most recent call last):
  File "/home/hoanghiep/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/hoanghiep/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/hoanghiep/miniconda3/lib/python3.6/site-packages/autokeras/search.py", line 296, in train
    verbose=verbose).train_model(**trainer_args)
  File "/home/hoanghiep/miniconda3/lib/python3.6/site-packages/autokeras/model_trainer.py", line 64, in __init__
    self.model.to(self.device)
  File "/home/hoanghiep/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in to
    return self._apply(convert)
  File "/home/hoanghiep/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/hoanghiep/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/hoanghiep/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 377, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error (10): invalid device ordina
```

### Reproducing Steps

+ Step 1: Choose 1 GPU to use (among 8 GPUs):

```
export CUDA_VISIBLE_DEVICES='7'
```

+ Step 2: Run the MNIST example on https://autokeras.com/start/#example page

```
# autokeras_mnist.py
python autokeras_mnist.py
```

### Expected Behavior

Succeed in running the MNIST example without this error

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 16.04
 - Python:  3.6 (Anaconda)
 - autokeras: 0.2.14
 - scikit-learn: 0.19.1
 - numpy: 1.15.1
 - keras: 2.2.2
 - scipy: 1.0.1
 - tensorflow: 1.10.0
 - pytorch: 0.4.1

**Comment by jhfjhfj1** [comment]
@tl-yang Would you change the auto GPU selection to only select from the CUDA_VISIBLE_DEVICES pool?
Thanks.

**Comment by jhfjhfj1** [comment]
@hiepph This one is fixed in the develop version. Will be in the next release.
Thanks.
