### ISSUE TITLE
Compress image before feed to NN if image is too large

### ISSUE THREAD

**Issue by aojue1109** [jhfjhfj1/autokeras#193]
### Bug Description

I did a cat and dog image classification task, only used 100 pictures to train, and a RuntimeError appeared on a single 8GB system: $ Torch: not enough memory: you tried to allocate 0GB. The image input is 100 * 224 * 224 *3. This problem occurs. The input standard for reducing the image is 100 * 32 * 32 * 3. This problem is not the case, but the accuracy is very low for the training result. The final evaluation value of the second classification. Less than 0.6.
The specific issues are as follows:

```
╒==============================================╕
|               Training model 1               |
╘==============================================╛
Using TensorFlow backend.
Current Epoch:   0%|                             | 0/1 [00:00<?, ? batch/s]Exception ignored in: <bound method tqdm.__del__ of Current Epoch:   0%|                             | 0/1 [07:59<?, ? batch/s]>                                                   
Traceback (most recent call last):
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.close()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/autokeras/search.py", line 296, in train
    verbose=verbose).train_model(**trainer_args)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/autokeras/model_trainer.py", line 103, in train_model
    self._train()
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/autokeras/model_trainer.py", line 147, in _train
    outputs = self.model(inputs)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/autokeras/graph.py", line 610, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 66, in forward
    exponential_average_factor, self.eps)
  File "/root/anaconda3/envs/automl-formal/lib/python3.6/site-packages/torch/nn/functional.py", line 1254, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at [/pytorch/aten/src/TH/THGeneral.cpp:204]
```

### Reproducing Steps
  * Step 1: Choose 1 CPU to use (among 8 CPUs):
  * Step 2: Run the Cat and Dog Wars classification task, select 50 cats and 50 dogs for the classification task, enter the image parameters: 100 * 224 * 224 *3

### Expected Behavior

Succeed in running the classification task without this error
Image classification accuracy increased to an acceptable greater than 80%

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.6
 - autokeras: 0.2.14
 - scikit-learn:0.19.1
 - numpy:1.14.5
 - keras:2.2.2
 - scipy:1.1.0
 - tensorflow:1.10.1
 - pytorch:

**Comment by jhfjhfj1** [comment]
@satyakesav 
First, you may examine whether the data is loaded to GPU memory batch by batch, or all together.
If is loaded all together, try to change it to load batch by batch.

Second, if the image is oversize (the total size is larger than 64*64*3), resize the image before feed into the NN, according to their original length/width ratio. Keep the size just right.

Thanks.
