### ISSUE TITLE
Cannot Run Example Code

### ISSUE THREAD

**Issue by wufaxiang** [jhfjhfj1/autokeras#210]
Hi, thanks for the amazing job.
But I cannot run the [examples/mnist.py] (https://github.com/jhfjhfj1/autokeras/blob/master/examples/mnist.py) successfully.
My python version is 3.6.
The error result look like the following:
```
Using TensorFlow backend.

Initializing search.
Initialization finished.

Traceback (most recent call last):
  File "ts.py", line 10, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "/home/faxiang/anaconda3/lib/python3.6/site-packages/autokeras/image_supervised.py", line 239, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "/home/faxiang/anaconda3/lib/python3.6/site-packages/autokeras/image_supervised.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "/home/faxiang/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 172, in search
    print('\u2552' + '=' * 46 + '\u2555')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2552' in position 0: ordinal not in range(128)
```
Is this an encoding problem? How to fix it?

**Comment by song3134** [comment]
Thanks for the comment. Please refer to #195.

**Comment by wufaxiang** [comment]
Ok, it works, thank you.
