### ISSUE TITLE
No module named 'autokeras.text'

### ISSUE THREAD

**Issue by VictorZhang2014** [jhfjhfj1/autokeras#257]
Errors Message Here:
```
Using TensorFlow backend.
/Users/user/virtualenvlist/dlp3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
Traceback (most recent call last):
  File "testautoml.py", line 2, in <module>
    from autokeras.image_supervised import ImageClassifier
  File "/Users/user/virtualenvlist/dlp3/lib/python3.7/site-packages/autokeras/__init__.py", line 2, in <module>
    from autokeras.text.text_supervised import TextClassifier
ModuleNotFoundError: No module named 'autokeras.text'
```
What the list of my pip is as below:
```
Package             Version  
------------------- ---------
absl-py             0.5.0    
astor               0.7.1    
autokeras           0.2.18   
certifi             2018.8.24
chardet             3.0.4    
cycler              0.10.0   
gast                0.2.0    
grpcio              1.15.0   
h5py                2.8.0    
idna                2.7      
Keras               2.2.2    
Keras-Applications  1.0.6    
Keras-Preprocessing 1.0.5    
kiwisolver          1.0.1    
Markdown            3.0.1    
matplotlib          3.0.0    
numpy               1.15.2   
pandas              0.23.4   
Pillow              5.3.0    
pip                 18.1     
protobuf            3.6.1    
pyparsing           2.2.2    
python-dateutil     2.7.3    
pytz                2018.5   
PyYAML              3.13     
requests            2.19.1   
scikit-learn        0.20.0   
scipy               1.1.0    
setuptools          39.1.0   
six                 1.11.0   
sklearn             0.0      
tensorboard         1.11.0   
tensorflow          1.11.0   
termcolor           1.1.0    
torch               0.4.1    
torchvision         0.2.1    
tqdm                4.26.0   
urllib3             1.23     
Werkzeug            0.14.1   
wheel               0.32.1   
```

Especially, TensorFlow I've tried to run both versions of 1.9.0 and 1.11.0, all are failed. Error info said No module named 'autokeras.text'
```
tensorflow          1.11.0
Keras               2.2.2   
```
Any helps is appreciated~

**Comment by wekinu** [comment]
in my case, when it reinstall, worked :)
