### ISSUE TITLE
The program is stucked in "training model 0"

### ISSUE THREAD

**Issue by zhoukaisheng** [jhfjhfj1/autokeras#297]
### Bug Description

The program is stucked in "training model 0"
I'm dealing with a binary classification problem with a sample size of (80,80,16) of almost 300 samples.

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.6
 - autokeras: 
 - scikit-learn:0.19.1
 - numpy:1.15.2
 - keras:2.2.2
 - scipy:1.1.0
 - tensorflow:1.11.0
 - pytorch:

### Additional context

![image](https://user-images.githubusercontent.com/43432335/48055857-86cdd280-e1eb-11e8-88e9-767eaded0e4e.png)

**Comment by tl-yang** [comment]
@zhoukaisheng Hi, thank you for reporting to us. Do you mind tell us what's your OS platform and which version of autokeras you're now using?

**Comment by zhoukaisheng** [comment]
win10.
autokeras's version,i don'k know how to get.
but the code get the new Bug:

Traceback (most recent call last):

  File "<ipython-input-7-68b06ee81421>", line 1, in <module>
    runfile('C:/Users/75129/Desktop/mypy/my model.py', wdir='C:/Users/75129/Desktop/mypy')

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/75129/Desktop/mypy/my model.py", line 156, in <module>
    clf.fit(train_x,train_y,time_limit=1*60)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\site-packages\autokeras\image_supervised.py", line 239, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\site-packages\autokeras\image_supervised.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data, timeout)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\site-packages\autokeras\search.py", line 178, in search
    pool = mp.Pool(1)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)

  File "C:\Users\75129\AppData\Local\conda\conda\envs\keras1\lib\multiprocessing\spawn.py", line 173, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)

AttributeError: module '__main__' has no attribute '__spec__'

**Comment by jhfjhfj1** [comment]
I believe this issue is solved. Feel free to reopen if still exists.
