### ISSUE TITLE
Failed to run examples/mnist.py

### ISSUE THREAD

**Issue by fangyiwang** [jhfjhfj1/autokeras#31]
Running examples/mnist.py
and got the following error:

...
Father ID:  2
[('to_wider_model', 1, 64), ('to_wider_model', 1, 128), ('to_wider_model', 1, 256), ('to_wider_model', 1, 512), ('to_conv_deeper_model', 6, 3), ('to_add_skip_model', 6, 19), ('to_conv_deeper_model', 1, 5), ('to_conv_deeper_model', 11, 5), ('to_wider_model', 19, 64), ('to_wider_model', 11, 64), ('to_conv_deeper_model', 25, 3), ('to_add_skip_model', 19, 11), ('to_wider_model', 1, 1024), ('to_conv_deeper_model', 33, 3)]
Traceback (most recent call last):
  File "mnist.py", line 12, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "/home/fayw/anaconda3/lib/python3.6/site-packages/autokeras/classifier.py", line 219, in fit
    run_searcher_once(train_data, test_data, self.path)
  File "/home/fayw/anaconda3/lib/python3.6/site-packages/autokeras/classifier.py", line 41, in run_searcher_once
    searcher.search(train_data, test_data)
  File "/home/fayw/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 168, in search
    new_graph, new_father_id = self.maximize_acq()
  File "/home/fayw/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 229, in maximize_acq
    getattr(nm_graph, args[0])(*list(args[1:]))
  File "/home/fayw/anaconda3/lib/python3.6/site-packages/autokeras/graph.py", line 311, in to_conv_deeper_model
    new_layers = deeper_conv_block(target, kernel_size, self.weighted)
  File "/home/fayw/anaconda3/lib/python3.6/site-packages/autokeras/layer_transformer.py", line 11, in deeper_conv_block
    n_filters = conv_layer.filters
AttributeError: 'StubDropout' object has no attribute 'filters'

Please help!

**Comment by jhfjhfj1** [comment]
This is fixed in the latest release.
Please reopen the issue if it is not.

Thank you.
