### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by codecrack3** [jhfjhfj1/autokeras#349]
### Bug Description
I'm training model and get an exception when  i using google colab :(

+----------------------------------------------+
|               Training model 4               |
+----------------------------------------------+
Process ForkProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/search.py", line 289, in train
    model = graph.produce_model()
  File "/usr/local/lib/python3.6/dist-packages/autokeras/nn/graph.py", line 564, in produce_model
    return TorchModel(self)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/nn/graph.py", line 653, in __init__
    set_stub_weight_to_torch(self.graph.layer_list[index], layer)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/nn/layers.py", line 468, in set_stub_weight_to_torch
    stub_layer.export_weights(torch_layer)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/nn/layers.py", line 84, in export_weights
    torch_layer.weight.data = torch.Tensor(self.weights[0])
TypeError: 'NoneType' object is not subscriptable

**Comment by jhfjhfj1** [comment]
@codecrack3 Thanks for the bug report. May I know which version are you using and what code are you running? Thanks.

**Comment by codecrack3** [comment]
I using version 0.3.3 and ImageClassifier method

**Comment by codecrack3** [comment]
I using version 0.3.3 and ImageClassifier method

**Comment by jhfjhfj1** [comment]
@codecrack3 I think the bug is fixed. You can try with 0.3.4. If it still has this error, please reopen the issue. Thank you!
