### ISSUE TITLE
RuntimeError: CUDA error (3): initialization error (google colab)

### ISSUE THREAD

**Issue by codecrack3** [jhfjhfj1/autokeras#355]
### Bug Description
When i exported model with method ImageClassifier, i get an exception 

100%|██████████| 243/243 [00:04<00:00, 54.86it/s]
100%|██████████| 275/275 [00:05<00:00, 46.61it/s]
(518, 64, 64, 3) (518, 1)
Preprocessing the images.
Preprocessing finished.

Initializing search.
Initialization finished.

+----------------------------------------------+
|               Training model 0               |
+----------------------------------------------+
Process ForkProcess-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/search.py", line 277, in train
    raise e
  File "/usr/local/lib/python3.6/dist-packages/autokeras/search.py", line 270, in train
    verbose=verbose).train_model(**trainer_args)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/nn/model_trainer.py", line 77, in __init__
    self.model.to(self.device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 379, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 377, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error (3): initialization error

**Comment by jhfjhfj1** [comment]
@boyuangong would you please look into this issue and try to solve it and include in the tutorial for export models? Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by boyuangong** [comment]
Hi @codecrack3 , thanks for your interesting in our package. I test the code on Google Colab and I didn't get any errors. 

As for your errors, it seems to be a pytorch problem which has something to do with `torch.manual_seed`, and it was fixed in pytorch [issue 2571](https://github.com/pytorch/pytorch/issues/2517 ), please take a look if you are interested. So my suggestion is try to make sure the torch version is the latest. 

Also, I have added the example of export and load keras model in example folder.

If you still get this problem, please feel free to let us know. And please add your settings such that we can repeated the bug. 

Thanks,
Boyuan
