### ISSUE TITLE
mnist example fails

### ISSUE THREAD

**Issue by PiotrMi** [jhfjhfj1/autokeras#42]
`C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Initializing search.
Initialization finished.
Training model  0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\search.py", line 323, in train
    verbose).train_model(**trainer_args)
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\utils.py", line 121, in train_model
    self._train(train_loader, epoch)
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\utils.py", line 140, in _train
    outputs = self.model(inputs)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\graph.py", line 577, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
TypeError: 'float' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mnist.py", line 10, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\classifier.py", line 224, in fit
    run_searcher_once(train_data, test_data, self.path)
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\classifier.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data)
  File "C:\Users\Adam\Desktop\autokeras\autokeras\examples\autokeras\search.py", line 187, in search
    accuracy, loss, graph = train_results.get()[0]
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
TypeError: 'float' object cannot be interpreted as an integer
`

mnist.py execution fails.

Windows 10
Python 3.6.2

**Comment by a1041134926** [comment]
I had the same problem，Please answer。

**Comment by a1041134926** [comment]
I have the same problem

**Comment by jhfjhfj1** [comment]
This issue has been fixed in the new release.

Thank you for the contribution.

**Comment by alessandropadrinofficial** [comment]
Same problem even with the new release
