### ISSUE TITLE
Exception occurred at train() : Input contains NaN, infinity or a value too large for dtype('float32').  when run example/task_modules/image/cnn_mnist_regression.py 

### ISSUE THREAD

**Issue by ghmole** [jhfjhfj1/autokeras#554]
### Bug Description
I try to run  'example/task_modules/image/cnn_mnist_regression.py'
but this exception happens:

Exception occurred at train() : Input contains NaN, infinity or a value too large for dtype('float32').
 
 ### Expected Behavior
Traceback (most recent call last):
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/autokeras/search.py", line 343, in train
    verbose=verbose).train_model(**trainer_args)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/autokeras/nn/model_trainer.py", line 138, in train_model
    test_loss, metric_value = self._test()
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/autokeras/nn/model_trainer.py", line 216, in _test
    return test_loss, self.metric.compute(all_predicted, all_targets)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/autokeras/nn/metric.py", line 47, in compute
    return cls.evaluate(prediction, target)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/autokeras/nn/metric.py", line 51, in evaluate
    return mean_squared_error(target, prediction)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/sklearn/metrics/regression.py", line 239, in mean_squared_error
    y_true, y_pred, multioutput)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/sklearn/metrics/regression.py", line 77, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False)
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/sklearn/utils/validation.py", line 573, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/ukxu/anaconda3/envs/ak/lib/python3.6/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python:                  3.6.8
 - autokeras:              0.3.6
 - scikit-learn:            0.20.1
 - numpy:
 - keras:                     2.2.4
 - scipy:
 - tensorflow:            1.12.0 
 - pytorch:                 0.4.1

**Comment by rebouvet** [comment]
I'm having the same issue on the example and on any regression I tried, even if i'm using `numpy.nan_to_num` on the inputs.

**Comment by jhfjhfj1** [comment]
@boyuangong Would you please look into this bug? Thanks.

**Comment by boyuangong** [comment]
This issue is because the learning rate is too large and cause the gradient explored. I just change the learning rate in the trainer to a smaller number. It tests fine now. In the future we may add customizable training args include learning rate feature to users.

**Comment by rebouvet** [comment]
Thanks for your response @ghmole!
Wouldn't be a good fix to implement some kind of gradient clipping?
