### ISSUE TITLE
RuntimeError: Given groups=1, weight[64, 4, 3, 3], so expected input to have 4 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by GagaLeung** [jhfjhfj1/autokeras#56]
Hi, my input tensor was in shape [batch, 20, 20, 1] and got this error:
---------------------------------------------
Traceback (most recent call last):
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/search.py", line 327, in train
    verbose).train_model(**trainer_args)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/utils.py", line 122, in train_model
    self._train(train_loader, epoch)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/utils.py", line 143, in _train
    outputs = self.model(inputs)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/graph.py", line 603, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight[64, 4, 3, 3], so expected input[128, 1, 20, 20] to have 4 channels, but got 1 channels instead
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "autokeras_alter.py", line 35, in <module>
    clf.fit(X_train, y_train, time_limit=24*60*60)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/classifier.py", line 225, in fit
    run_searcher_once(train_data, test_data, self.path)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/classifier.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data)
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/site-packages/autokeras/search.py", line 190, in search
    accuracy, loss, graph = train_results.get()[0]
  File "/public/users/liangqiaoxing/.conda/envs/tensorflow_py3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Given groups=1, weight[64, 4, 3, 3], so expected input[128, 1, 20, 20] to have 4 channels, but got 1 channels instead

------------------------------------------------

The error message seemed to come from Torch. I tried running the same ImageClassifier code on mnist data with shape  [batch, 28, 28, 1] and the code worked fine. 

Here is my training set. Does anyone know why or meet the same error? Thanks!
[demo.zip](https://github.com/jhfjhfj1/autokeras/files/2264905/demo.zip)

**Comment by pramod2157** [comment]
I am facing the same issue

**Comment by jhfjhfj1** [comment]
@GagaLeung Would you please share your code as well?

Thank you!

**Comment by GagaLeung** [comment]
Here's my code: 
----------------------------------------------------------------------
from autokeras.classifier import ImageClassifier
import argparse
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument('-path', dest='path', type=str, help='/path/to/save/model')

args = parser.parse_args()
path = args.path

if __name__ == '__main__':
    x_train = np.load('x_train.npy')
    y_train = np.load('y_train.npy')
    clf = ImageClassifier(verbose=True, path=path, resume=True, augment=False)
    clf.fit(x_train, y_train, time_limit=12*60*60)

**Comment by GagaLeung** [comment]
[autokeras_bugcode.txt](https://github.com/jhfjhfj1/autokeras/files/2289362/autokeras_bugcode.txt)
Here's the text file version of the code, since the format was changed by the message board.
Thanks!

**Comment by jhfjhfj1** [comment]
@tl-yang 
Add some code in the second last line in train() function in search.py.
to remove the model from the GPU memory.

Be careful about the import weights in layers.py and the loss returned by train_model() function in utils.py should be a float instead of a tensor.

**Comment by jhfjhfj1** [comment]
@GagaLeung I think this issue is fixed in the new release of Auto Keras.
Please repoen the issue if it is not.

Thank you for your report.
