### ISSUE TITLE
Failed to run the /examples/a_simple_example/mnist.py

### ISSUE THREAD

**Issue by LuneZ99** [jhfjhfj1/autokeras#596]
### Bug Description
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\search.py", line 327, in train
    verbose).train_model(**trainer_args)
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\utils.py", line 122, in train_model
    self._train(train_loader, epoch)
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\utils.py", line 143, in _train
    outputs = self.model(inputs)
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\graph.py", line 603, in forward
    temp_t...

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    
vspd.debug(filename, port_num, debug_id, debug_options, run_as)

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 37, in debug
    
run(address, filename, *args, **kwargs)

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 64, in run_file
    
run(argv, addr, **kwargs)

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_local.py", line 125, in _run
    
_pydevd.main()

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1752, in main
    
globals = debugger.run(setup['file'], None, None, is_module)

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1099, in run
    
return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\pydevd.py", line 1106, in _exec
    
pydev_imports.execfile(file, globals, locals)  # execute the script

  File "d:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    
exec(compile(contents+"\n", file, 'exec'), glob, loc)

  File "E:\LuneZ99\python\autokeras_learning\autokeras_learning\autokeras_learning.py", line 10, in <module>
    
clf.fit(x_train, y_train, time_limit=30 * 60)

  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\classifier.py", line 225, in fit
    
run_searcher_once(train_data, test_data, self.path)

  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\classifier.py", line 40, in run_searcher_once
    
searcher.search(train_data, test_data)

  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\site-packages\autokeras\search.py", line 190, in search
    
accuracy, loss, graph = train_results.get()[0]

  File "D:\ProgramData\Anaconda3\envs\AutoML\lib\multiprocessing\pool.py", line 644, in get
    
raise self._value

**TypeError
:** 
**conv2d(): argument 'padding' must be tuple of ints, but found element of type float at pos 1**

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows10
 - Python: 3.6(anaconda)
 - autokeras: 0.2.0
 - scikit-learn:0.19.1
 - numpy:1.14.6
 - keras:2.2.4
 - scipy:1.1.0
 - tensorflow:1.12.0
 - pytorch:1.0.1

### Additional context
I've looked at some other issues but none of them can be helpful.

**Comment by LuneZ99** [comment]
I changed to  pytorch 0.4.1, but got **'float' object cannot be interpreted as an integer** this time.

**Comment by LuneZ99** [comment]
do not use 'pip install autokeras' , just download the code from the GitHub repo and run the setup commands, it can solve all problems.
