### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by lichunhong2010** [jhfjhfj1/autokeras#64]
Traceback (most recent call last):
  File "C:/Users/lichunhong/Desktop/python_code/autokeras_try/1.py", line 10, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\classifier.py", line 225, in fit
    run_searcher_once(train_data, test_data, self.path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\classifier.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\search.py", line 190, in search
    accuracy, loss, graph = train_results.get()[0]
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

TypeError: 'float' object cannot be interpreted as an integer

**Comment by igouvea** [comment]
Having the same problem here. Couldn't install with 'pip install autokeras', so I installed with --no-dependencies. Then installed the dependencies manually (wrong versions). Could be that. But I am having the same problem on windows. Under Linux Subsystem it worked perfectly.
